language: java
jdk: oraclejdk8

install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report
    mvn test -B

services:
  - postgresql
  
before_script:
  - psql -c 'create database schooldiary;' -U postgres
after_success: 
  - mvn clean test jacoco:report coveralls:report 