language: java
jdk: oraclejdk8

script:
  - mvn test jacoco:report

services:
  - postgresql
  
before_script:
  - psql -c 'create database schooldiary;' -U postgres
after_success: 
  - mvn clean test jacoco:report coveralls:report 